#ENC[AES256_GCM,data:SblTTbYE0oDi1IakYlEj603fQqQPrrM5uYPqKpKRfQ==,iv:wK5hVa2BywCbH9rliSBFaDpTBcLe1pTkIWI7c2FO9Tc=,tag:lmdEp7xtWOuqaD5s02/MiQ==,type:comment]
#ENC[AES256_GCM,data:1JtC2mWW5GgWkDMjHWf+vHAxs3qdMbRnvbv70kQgMg==,iv:SxU+adgzxlqkpil1AjbJia3JNz+iXUMu0qUXni7aP48=,tag:CAPyO9+oFbPyeW5c12Ktng==,type:comment]
#ENC[AES256_GCM,data:EYD2JTDZKY8BZCP5KhIjFpafHz2Gio0Eyv7rgl8TR4hCWe3te4ESJRspzXOf9BM0aUKyng==,iv:uCHjAgg69JH8DlkyQbEQ4CYVgTcU04SeRoBIR/uvkSw=,tag:ZMCSF7+KSnA1V0Kk1XZOvw==,type:comment]
replicaCount: ENC[AES256_GCM,data:PA==,iv:YNnCpD1NpQTUrD7x5qMOKtJuApsVMzuwgwRNiWSd5YU=,tag:Jh2uiQmCmZ/BWoisiO8O3A==,type:int]
nameOverride: ENC[AES256_GCM,data:CTQ5coJnqnhQrGrJBV98i7MaY0z4,iv:U7ruJz8APYP2m+cYWUpcFUHMGiso8IscrMKwC2DmyKY=,tag:TQKbGC3Wb9RCd5REUdI5TQ==,type:str]
fullnameOverride: ENC[AES256_GCM,data:0XYsrH20pBLiaebQmcQ=,iv:245dBasjqvwVMvgK4BG6VI82f2C1yuQLSo2E2a1yBPc=,tag:snv3vYfE2zGvmr2eS68SCA==,type:str]
containername: ENC[AES256_GCM,data:pObmFAkriP1q1hqmvD632RBscy4=,iv:rBwlyL65EV7NBUIOJ1LF79aL3jVDwnkdtFKx9NqLSsk=,tag:LigEMoZZOIrAhKno7U7OIg==,type:str]
image:
    repository: ENC[AES256_GCM,data:VQmGEV7aOBtYEPlWssIPU16GdLo=,iv:FekmsIT6jxuxO9YhiwpQPNQvitoPWZcGnmFwRTaQSUg=,tag:pwEOFaRdKB67Q6Mfm38TyQ==,type:str]
    pullPolicy: ENC[AES256_GCM,data:xfUgTnFW,iv:tYJgloEnn368F5BrMA3tjyifDMCmdH4Sj9xS0uEl1y4=,tag:1Z/c8at/WGcerI5bYJ3Maw==,type:str]
    #ENC[AES256_GCM,data:VbdI2tsj/c6m2vZSSeMaB3t5KaqurGGY72uChZe938VwBpMkAUfqtj6EEGePL6BwfCPPx+rNaQh/GVzix9Fj,iv:UkvDHp+423rVpaWVjbvlgWZ0hzPPZ2O8DKrTQBdbQW4=,tag:/C2Tpn+dYp2aYP/H+O0xJQ==,type:comment]
    tag: ENC[AES256_GCM,data:GGd5OXTV,iv:vGXmCTwbbkh0LbB+FZmPTqTGFP8zUQ1fcJ1CPHbtSu0=,tag:Y1NsUtv+kiYcAWD7UiMiJw==,type:str]
#ENC[AES256_GCM,data:Z7DV2jneFXLXh1C9+b89KI5i,iv:vYymZi77cdqSCOnGQn0NbPv/grZC+pg/UZZfGwjlUjE=,tag:FDoV20Gls36TcQ/BPK7n6Q==,type:comment]
#ENC[AES256_GCM,data:481hW4ehH4luq9MoluutTtOK5+ms0x8Ifw==,iv:k2qfSfZBE05hm9EiL0zwqAiO8ieTKxnohj+mNfynf0A=,tag:/VG4UXiULL383dCyhzf6Wg==,type:comment]
containerport: ENC[AES256_GCM,data:0V8=,iv:TRpEI3N8omfx+joylCCiyXtA0jLJjOChhwJD2f+wldg=,tag:F9i4qmw6/oS7aztDZmVd4A==,type:int]
serviceAccount:
    #ENC[AES256_GCM,data:iQEzl+shTnpK42g49L3VAyDNt95t8h68dwD4DZjTr6S6HNC14l0imHkzhsSpxgOX17FqLyvC,iv:ArJN8wl3a/K3gHDKxHUc843K2Zjrp5lI19bxBYisdBM=,tag:xAXcMsimrDR5w10qqngACg==,type:comment]
    create: ENC[AES256_GCM,data:r+TQBtc=,iv:6liIoNQusciMkqghIxPMBUok5H9eCjnw8ZmfT1jGV6c=,tag:5ikm/QPLMUrXjnAhlGkFpw==,type:bool]
    #ENC[AES256_GCM,data:R9sCyhyat8bxr6060GjaR+uCxIlDYSgYYqiMrv47Zuk2H9cQOmJL0Dio8SgMSZAqvf3AJS6E47I=,iv:4CpyKSyi+Q4Ai6sZ6Y1SRebSrNFoBaiMSxbWcp1gzYY=,tag:8xr9RTPwtyAfXNSLhn7D8w==,type:comment]
    automount: ENC[AES256_GCM,data:lBx7VQ==,iv:JI48BGSNfWDuHhMnZxm/v2eBU+zK8DOTjzU4t1TnG64=,tag:zmA6Rdc3blJjwt4+FzUdXw==,type:bool]
    #ENC[AES256_GCM,data:h2qWqAfjt1DkyygjMqhQ6jA4Xq+RGBdpVwZM+1wrUNomCC7NnF7YHfbM,iv:9IbuiO+GHC5Xqd8Fe4z8htUEoenHGvoEoBB7W/pWVqo=,tag:d2wUyFzZkuOklgy8xX5cIw==,type:comment]
    annotations: {}
    #ENC[AES256_GCM,data:2xq5B6m8wzLzyfwY4jZ1HVXZ4iW4c/a0RKofSsFJLl+OAECrQMAPrA==,iv:06uOPPl6Y6VySzVWn6SkZFkcDowT2ABVQM6kHP0OCmY=,tag:BMGvNXpY2PdD2f+vxRQ7/w==,type:comment]
    #ENC[AES256_GCM,data:y9xW+jz0vbC02GSK+w1JX1MtvqAavgU5hV5Wh80WVZuMVQNiJvBO+ikvJYbCXTfbVFcelzdAyBWxCAzN48GYyJ+E4w/SzBdmLjkZ8sJZBA==,iv:xAlZEyhMSbe1a6niCZbh9CDeFqsogwoA4Z/kcJFslb8=,tag:0r9s0ERmwdc8FGjhZlmM6w==,type:comment]
    name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
#ENC[AES256_GCM,data:CsyNRBVYtdakutdCG0I=,iv:dJXAdXJJ3XffPkn6iTnqKIyUR5X6t9kOFVKn3kU2htk=,tag:qV6KI6aRc0HwOAcLxyz3Aw==,type:comment]
#ENC[AES256_GCM,data:hnbgHS/rp+Vm9pJJs9PxybM=,iv:gX6xua7YvMXTYA3rYL19nvc18Dc8lVzRDLhtU332a38=,tag:orkJPHLKUFOQDcnm+ynzzg==,type:comment]
#ENC[AES256_GCM,data:v/o8A7pMuKD+EO1knfzsxA==,iv:dPyO/8UY00G929h/K6ueChPIumzNczph6yyS8o/9BYk=,tag:amb5RKoLudXqN/upEL96NQ==,type:comment]
#ENC[AES256_GCM,data:KbzwcWJ8XB12Mw==,iv:N1GtOmdb7ydnGW3e+ZeZL/bM2lsiaXOHjzXLJS7qhYs=,tag:YUx75RiGXRzIZc3gCPC2KQ==,type:comment]
#ENC[AES256_GCM,data:FWLPDy0kDuZ1JA==,iv:SmOcxFSM52wSSES0eKTltdFnyE00gHMyvPgILxhZexM=,tag:2p3w0sDItJqIa0oj/xNCzg==,type:comment]
#ENC[AES256_GCM,data:QMRG6GrjFkrd+X+j5sH3T1RYDa76Y5BNNBPqAsKVgbsq,iv:/zOicLtQqJ2/TvOEgVwaAwZPxrVYbL8pmsGVypxd+aI=,tag:8oOqagwzfOOp5pE+ZlzJyA==,type:comment]
#ENC[AES256_GCM,data:d75DsXN53pM+agj9dK1Frv6yUJQN,iv:a6Se4nbDjUWvr2F5cHJrDyBkOp3wwj22Ae2398EAEc8=,tag:NQSDnmTRIXXedjoYnNf4Hg==,type:comment]
#ENC[AES256_GCM,data:11Xii2p3TSH2d2v+6kEyn5vRBjU=,iv:VJ3XnQEYFaf+sUYtvSH+8UrHfB19SDTeYhxMnaauyLg=,tag:Hfe7vqI115SPIjR1Fi5h3Q==,type:comment]
service:
    name: ENC[AES256_GCM,data:FAp3htKgtLEfWU0/aLDuyjad,iv:MmozKjAiHp7DI3xZM4Rv+dxxCLoo8xB/W6tbGuL0viw=,tag:NiTol2Ge9uMUZcmRuQXJHg==,type:str]
    type: ENC[AES256_GCM,data:48WWwGWKX9cM,iv:PFIwv7rxBTB6ew6UbpA1kx8UQz4emniNzoCZa0tmDto=,tag:FsCAmWfYcd+WMa33uWwMAw==,type:str]
    port: ENC[AES256_GCM,data:3Ks=,iv:AXanbZAvSgqKqY5YxZGkYEErWgpRCCW9WE8cBCyglrA=,tag:bn+0oCaS9GG/GkfTRfzzkA==,type:int]
ingress:
    enabled: ENC[AES256_GCM,data:/6icVg==,iv:iC2oUnoGoAW9507AtmDijM6oMn1CHwjpQFapwh1f1GA=,tag:WiBklYI52BwzwiRmwjRl8w==,type:bool]
    className: ""
    annotations: {}
    #ENC[AES256_GCM,data:y2E0+WBOrdFc2tvlCsqaCq4M2SIRC37bXnNwyUmcSkinhbY=,iv:0IbLKTMSaIGaaB/Bkei17MMtCkelKCpxhUDNCHWEOKI=,tag:5wcWa8KOdald4F2LF0viMw==,type:comment]
    #ENC[AES256_GCM,data:/RRvNdXCBabxl46c37i2rr4GEuWJuY6h8fGIZuKJow==,iv:sLtJQA+d37LjowGFaF2xNhc8pz+MdBiJC60n/RaFofo=,tag:UBXOy5WvEV4XlLQ91byw8A==,type:comment]
    hosts:
        - host: ENC[AES256_GCM,data:+a46IdAysB/zINRRjZhkdwocqhYqHw==,iv:o28OF3WE+l026xS2q2t5FooB5omnItCSeC2XPrFh6T0=,tag:cXo2UIiQ2XpVwWqGg/TtGA==,type:str]
          paths:
            - path: ENC[AES256_GCM,data:iA==,iv:HhlLrL5OljdwJ2LfAPrBE1bB89ZOOjwB5nYW5l8uc0s=,tag:nTF+o7CEiWQCRfZQp9EEDg==,type:str]
              pathType: ENC[AES256_GCM,data:mq12Da7reN1EjJ6Hgzq1TJC8Iiar4A==,iv:BJUiqF8xPJ/KpoksKUP5eISdP9PP9KMVj+a4P3ucIIc=,tag:zUD2gxlP7W+ZHKKVJoIy7w==,type:str]
    tls: []
    #ENC[AES256_GCM,data:qVRwidwY8uUr8JN1cajzM4Jy69a7nI73SjhQLcxsT5Lr,iv:LxSmJ6XzlMAHLg8y3+OFNcfeHkd2AZKolany8LpsPm4=,tag:c93m0kbPy1H0EaqxhEiSGA==,type:comment]
#ENC[AES256_GCM,data:kmECdeFRbgoaZA==,iv:SRbtM7nP6LhY7nxpHf360E3S47OcaECfWl1pzD8RxZ8=,tag:hWVd7B6QAYVDHdd+ciUWkA==,type:comment]
#ENC[AES256_GCM,data:QKi21cmLRSoGFQ46AXznUUQnPjg0lkzY5Bl1,iv:7Sjdff4KkEDKeKt9V1VhZm9V7DfqQG0whgGH0OJ5qSk=,tag:QzzlYQQfvhi+tgcBav49zA==,type:comment]
resources:
    limits:
        memory: ENC[AES256_GCM,data:5AGbbq4=,iv:0eR9nUVMMLVr9Hd/Ruam5P11XaOrglTFgtMWg2m2wWg=,tag:rSnYa1NWaGL5KJU8W3ZRJA==,type:str]
        cpu: ENC[AES256_GCM,data:2Q==,iv:wxqKNbCoJSVIlfIfxbaUoV2PDDSH61yehCVDnxSY1a8=,tag:Z5d3/qFTD7A5kmZdC/2BMg==,type:str]
    requests:
        memory: ENC[AES256_GCM,data:q1HBGAw=,iv:3SKYZnnLwWS7wswHq13p1QhYKel0LuzOW3M2JkyVJsI=,tag:GTQiFevaampkVe1s2Rdl2w==,type:str]
        cpu: ENC[AES256_GCM,data:cWMM,iv:3k/HbzYpfgllxWrjx4phyhViWNfQ5Hozzz5bZbByHYc=,tag:T6fyF+/E/ntw4OOIYJbXxA==,type:str]
autoscaling:
    enabled: ENC[AES256_GCM,data:WyqaEfU=,iv:wFPLPmFOjZQYWkPbL502yejPqgxB8Lx79lxmhhETL6w=,tag:SyyVSsrnXi5XMrCsbb9azg==,type:bool]
    minReplicas: ENC[AES256_GCM,data:8A==,iv:xFu7Z649BmG667pYuIEMz3zgdzQV9nW4ntbeVxcKJ0s=,tag:L5RMjLusiwrAtA6mASAq1Q==,type:int]
    maxReplicas: ENC[AES256_GCM,data:FYUr,iv:8i/e3mtHHTwJcPmu/NO7RCda+qXp+4Dy/7LVBJXL/uY=,tag:6rh2xgSOF7YJAoL/VHghJA==,type:int]
    targetCPUUtilizationPercentage: ENC[AES256_GCM,data:GTY=,iv:rZ8yOd6xjKj2fd/Qnk7k67t5cna3hvRAcBvuOcdG7NI=,tag:bPAMIdNK7ZP1ugSxDVJg3w==,type:int]
    #ENC[AES256_GCM,data:2OMhxVJskfBAEPnVUJEudLdDg2+Iw37s5t/Stper6pFaAYUDjec=,iv:bHOAoiLmRL1Z4MzjK+ZxGzNbg2C1asYRj7qnlY8vcoo=,tag:KHbTC9gSjzho6QwykKJEhg==,type:comment]
#ENC[AES256_GCM,data:Eih9OTzu/DPeuupvpRgTkGyzG6F2bqWz488fxjh4XTX+tE7IGiLVTgccdHCQIW3HmoYBlB2pf4Y=,iv:DKBl80hLe3jHbktp7fIvjBLSvL835ijj7541QJ5mCRY=,tag:UfLAjbqVHOD8yNkkF80uBg==,type:comment]
volumes: []
#ENC[AES256_GCM,data:BJrjZIwBADLeH2ZD,iv:6TnJ9G392EAqFpnmhezreuvGog285ZkHpCImxA/6Fog=,tag:2WBYzZ2FRuEw7t0uwzj5oQ==,type:comment]
#ENC[AES256_GCM,data:BJcI06wfivHmKA==,iv:Zq96mFY/jEagkWY6ld+E3U95GTNV4tQZLqi5DBGZm/8=,tag:K/ggupnRdRxaN7Whgf/ssA==,type:comment]
#ENC[AES256_GCM,data:CY1IYG657cRtwyinPR27iVeuJqSYJOCcJw==,iv:e6AtkbfqTKUBuFiXjaRsRCWgj1nJLhnB0ATGJw/GTD4=,tag:9QCqGlU3NEUYog9yqiy4+w==,type:comment]
#ENC[AES256_GCM,data:4x7d73YKV9ZYRgl2eAJzY7aVu/I=,iv:o1puT5dzd0ZcKgmxDPu1vaUwZJx2ZkoP+r4DIq7rRu8=,tag:ljQ9BrwvYjFZb860//S81w==,type:comment]
#ENC[AES256_GCM,data:mh1EZHgYTBmefEAckHk+d/OvKIUYuwa9ZjlMNh+HsGn/FdDzCq5K3jCK5WDYBbAd4k8wygR3W5VU3yXMJA==,iv:c9rUGBxazAZi4c6tfg5sMmNVky51GpXMj+RdfEqXJJc=,tag:LxpkGOysFIGqNOyqCMEX7A==,type:comment]
volumeMounts: []
#ENC[AES256_GCM,data:szwhiFxqvoKln68O,iv:elATmlQ1bMwMOiBYEp0WXPw0IYIYfxDoXyJtOV8d8hE=,tag:aDL9tBjQt2M0Y66EVIaJtg==,type:comment]
#ENC[AES256_GCM,data:6zbmpxzH5uxT4CPF8HRSL3ZiLhUrfXgl,iv:ndANqMoOAbbBw5utSpo+RFW3y0VB/Jl945Pn+pAd6jI=,tag:1yi7TUwoUy0fvcj4z40hwg==,type:comment]
#ENC[AES256_GCM,data:a7fB7//y5kvl+axfbj60M/U=,iv:n3hWqKBDvTK6y1rDBj+vQa7aY+eSgvQnRA7wRscWvnA=,tag:6ev0Z6AjGlKQjQdSNSjvBw==,type:comment]
nodeSelector: {}
tolerations: []
affinity: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0cuckkjzrmat65mf5ttedqqj972evmc9ex7zye892ctzsr0evpsg6p0z9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcUlmUW5BU0JuYnNjNTho
            RThwUkVZUk5vaFg5dlQ4b0xGNnpJVmF3Z1hRCjNlQm5ld0pBZzVicHFqOUJlMlI5
            cW5pQUdXSVY2RW5BRzduMzU0RnM5RUEKLS0tIDV2RHA1SEZNSFhTY3V3VEpTVWJW
            blVaL2REd3Noc3V5ZkI2T0tOMVdDY0EKmWHGCqzZ5HdG0jSEz+AkiaDzXraY9+ST
            B0DS6MhnN83tp8REQoi9RHqnuDRqujYE2i48bbZ3Pwc2D9SFyure8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T18:27:53Z"
    mac: ENC[AES256_GCM,data:lVhsbQSf9qXHVcEI5HK31hDYiJwX5RSbz+mGTgvAHEMxfa+52S6wIdaeqDC6BgBIvgcVVTxu6Y+gfAx+H453tswpmc8EPPs6UjRaDC30TbPEZoGPia3hQYzjE/5828GNOPLuEbUCMlP3cw7rPKkDTJLGUK0UeWWCoY2zFgfgSPw=,iv:xcsRz9MwNpbZ9cCGm0WnwbGLx0qIFIsvFNSD+dZqvWQ=,tag:m8tLSrZeWL2D23nKIem0zQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
